version: 2
jobs:
  build:
    working_directory: ~/enju_leaf
    docker:
      - image: circleci/ruby:2.4
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
      - image: circleci/postgres:9.6-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      - run: bundle update
      - run:
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:create RAILS_ENV=test
      - run: bundle exec rake db:migrate RAILS_ENV=test
      - run: bundle exec rake
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
